
title: "Jeff Vautin"
tagline: ""
description: "Follow <a href=\"https://micro.blog/jeff\">@jeff on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/jeff\">@jeff on Micro.blog</a>."
baseurl: ""
url: "http://micro.jeffvautin.com"
markdown: "kramdown"
username: "jeff"
microblog_user: "jeff"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jeff Vautin"
name: "Jeff Vautin"
gravatar_hash: "004ce6443ff2c0ec37adb5933fd43cda"
avatar: "https://micro.blog/jeff/avatar.jpg"
full_name: "Jeff Vautin"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "299"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"